sonar.projectKey=fabrizioperezperalta_recipeplatform
sonar.organization=fabrizioperezperalta
sonar.projectName=recipeplatform
sonar.projectDescription=RecipePlatform - Sistema de Recetas en Línea y Menús Personalizados

# .NET specific
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/test_results.trx

# SCM
sonar.scm.provider=git

# Source
sonar.sources=src/RecipePlatform.Domain,src/RecipePlatform.Application,src/RecipePlatform.Infrastructure,src/RecipePlatform.API
sonar.tests=tests
sonar.test.inclusions=**/*Tests.cs,**/*Test.cs

# Exclusions
sonar.exclusions=**/bin/**,**/obj/**,**/.github/**,**/wwwroot/**

# Quality Gate
sonar.qualitygate.wait=true